### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by j2l** [nilspettersson/website_node_editor_prototype#1]
Hello Nils!
I was looking for a node editor that was generating code and I found your simple project great!
It is quite educational "to see if ita worka lika me wanta"
It's a great idea that you made it without pre-made libraries. 

Do you plan to develop it for javacsript code too?

Did you use another easier solution?

Thanks!

**Comment by nilspettersson** [comment]
Hello @j2l!
This project has the prototype code, the most recent code can be found in https://github.com/nilspettersson/website_node_editor.

It has some support for javascript, but with a few issues. It is meant to make it possible to add some javascript events to elements.
I have not used any other solution.

**Comment by j2l** [comment]
Thanks!
Haha, Github's algo sent me here and not to your most recent project.
I'll have a look at your other project.
Closing for now.
